// Regenerates styles/themes.css from lib/themes/gen.ts.
//   node lib/themes/scripts/build-css.mjs      (Node >= 22.18, type stripping)
import fs from 'node:fs';
import { SEEDS, TOKENS, generate } from '../gen.ts';

const block = (sel, t) => `${sel} {\n  ${TOKENS.map((k) => `${k}: ${t[k]};`).join(' ')}\n}`;
const out = [
  '/* GENERATED by lib/themes/scripts/build-css.mjs. Do not edit by hand. */',
  '/* Palettes override the base tokens from app/globals.css. <html data-palette="<id>"> */',
  ':root[data-palette] { --header-grad: linear-gradient(180deg, var(--surface) 0%, var(--bg) 100%); }',
  "/* Defaults for the board tokens when no palette is chosen */",
  ":root[data-theme='dark'] { --board-bg: #12122a; --block-1: #f87171; --block-2: #fbbf24; --block-3: #facc15; --block-4: #4ade80; --block-5: #22d3ee; --block-6: #818cf8; --block-7: #e879f9; }",
  ":root[data-theme='light'] { --board-bg: #ececf6; --block-1: #f87171; --block-2: #fbbf24; --block-3: #facc15; --block-4: #4ade80; --block-5: #22d3ee; --block-6: #818cf8; --block-7: #e879f9; }",
];
for (const s of SEEDS) {
  for (const mode of ['light', 'dark']) {
    out.push(block(`:root[data-theme='${mode}'][data-palette='${s.id}']`, generate(s, mode)));
  }
}
const file = new URL('../../../styles/themes.css', import.meta.url);
fs.writeFileSync(file, out.join('\n') + '\n');
console.log(`wrote ${SEEDS.length} palettes x 2 modes -> styles/themes.css`);
