/**
 * Writes programs/blockbite-prize/tests/fixtures/ts-rounds.txt: two prize
 * rounds built entirely by the TypeScript side (results.ts payouts,
 * merkle.ts tree and proofs, prize-ix.ts PostResults and claim
 * instructions). The Rust test `ts_built_rounds_post_and_claim` replays these
 * exact instructions against the compiled program in LiteSVM.
 *
 *   npx tsx scripts/prize-fixture.ts
 *
 * Deterministic: the same code always writes the same file.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { Keypair, type TransactionInstruction } from '@solana/web3.js';
import { getAssociatedTokenAddressSync } from '@solana/spl-token';

const OUT = join(__dirname, '..', 'programs', 'blockbite-prize', 'tests', 'fixtures', 'ts-rounds.txt');

function wallet(label: string): string {
  return Keypair.fromSeed(createHash('sha256').update(`blockbite-fixture:${label}`).digest()).publicKey.toBase58();
}

function ixLine(tag: string, ix: TransactionInstruction): string {
  const metas = ix.keys.map((k) => `${k.pubkey.toBase58()}:${k.isSigner ? 's' : '-'}${k.isWritable ? 'w' : '-'}`);
  return [tag, ix.programId.toBase58(), Buffer.from(ix.data).toString('hex'), ...metas].join(' ');
}

async function main() {
  const { planRound, dailyPool, monthlyPool, leavesOf } = await import('../lib/ranked/results');
  const { buildTree, proofFor, rootOf, verifyProof } = await import('../lib/ranked/merkle');
  const { postRoundIxs, roundSpace, claimIxs } = await import('../lib/ranked/prize-ix');
  const { USDC_MINT } = await import('../lib/solana/config');
  const { PublicKey } = await import('@solana/web3.js');

  // Day: 12 wallets, a tie for 2nd/3rd and one across 10th place (11 winners).
  const dayScores = [9000, 7000, 7000, 5000, 4000, 3500, 3000, 2500, 2000, 1500, 1500, 100];
  const day = planRound('day', '2026-10-01', dailyPool(1_234_567_891n),
    dayScores.map((score, i) => ({ wallet: wallet(`day-${i}`), score })));
  // Month: only three wallets, so most of the curve stays unallocated.
  const month = planRound('month', '2026-10', monthlyPool([1_234_567_891n, 700_000n, 0n]),
    [12_000, 8_000, 4_000].map((score, i) => ({ wallet: wallet(`month-${i}`), score })));

  const lines = ['# generated by scripts/prize-fixture.ts; do not edit'];
  for (const plan of [day, month]) {
    const leaves = leavesOf(plan).map((l) => ({ wallet: l.w, amount: BigInt(l.a) }));
    const levels = buildTree(plan.roundId, leaves);
    const root = rootOf(levels);
    lines.push(`round ${plan.roundId} ${root.toString('hex')} ${plan.total} ${leaves.length} ${plan.kind} ${plan.period} pool=${plan.pool} unallocated=${plan.unallocated}`);
    leaves.forEach((l, i) => {
      const proof = proofFor(levels, i);
      if (!verifyProof(root, plan.roundId, i, l.wallet, l.amount, proof)) throw new Error('TS proof does not verify');
      lines.push(`leaf ${i} ${l.wallet} ${l.amount} ${proof.length ? proof.map((p) => p.toString('hex')).join(',') : '-'}`);
    });
    // Round account rent at the test runtime's default rate (6960 lamports per byte, 2 years).
    const rent = (128 + roundSpace(leaves.length)) * 6960;
    for (const ix of postRoundIxs(plan.roundId, root, plan.total, leaves.length, rent)) lines.push(ixLine('post', ix));
    leaves.forEach((l, i) => {
      const owner = new PublicKey(l.wallet);
      const ata = getAssociatedTokenAddressSync(USDC_MINT, owner);
      lines.push(`claim ${l.wallet} ${ata.toBase58()} ${l.amount}`);
      for (const ix of claimIxs(owner, plan.roundId, i, l.amount, proofFor(levels, i))) lines.push(ixLine('ix', ix));
    });
  }

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, lines.join('\n') + '\n');
  console.log(`wrote ${OUT}`);
  for (const p of [day, month]) {
    console.log(`  ${p.kind} ${p.period}: round ${p.roundId}, pool ${p.pool}, ${p.awards.length} winners, total ${p.total}, unallocated ${p.unallocated}`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
